### ISSUE TITLE
Path not exist issue with deployment, Pod stuck at ContainerCreating state

### ISSUE THREAD

**Issue by luanau** [DanWahlin/DockerAndKubernetesCourseCode#15]
Hi Dan, I think your course is great! Loved it. I found a minor issue I report here so it might help other students. Luan

https://github.com/DanWahlin/DockerAndKubernetesCourseCode/blob/773e11705c5f61b2cc73b1dc73af4f5f51aed9bc/samples/secrets/mongo.deployment.yml#L42

I had to change the two lines,
  local:
    path: "/c/temp/data/db"

To, 
  hostPath:
    path: "/c/temp/data/db"

For it to deploy without issue on Docker Desktop on Windows with WSL2.

Otherwise it get stuck at ContainerCreating state with error ,
  Warning  FailedMount  1s (x3 over 2s)  kubelet, docker-desktop  MountVolume.NewMounter initialization failed for volume "mongo-pv" : path "/c/temp/data/db" does not exist

**Comment by DanWahlin** [comment]
Thanks for the info. Really appreciate you reporting that. `local` is there because `hostPath` hasn't worked directly on Windows. But, I can add a comment about WSL there since now there are two options for running Kubernetes on Windows using Docker Desktop. Thanks again. :-)
