### ISSUE TITLE
path to local storage on windows

### ISSUE THREAD

**Issue by tom-canova-mckesson** [DanWahlin/DockerAndKubernetesCourseCode#16]
The readme for mongo.deployment.yml said to change the PVs local path to /c/temp/data/ but the path that I had to use was /run/desktop/mnt/host/c/temp/data/db    I'm using Docker Desktop for my Kubernetes

**Comment by DanWahlin** [comment]
Good to know. PVs on Windows have been a pain and haven't actually worked with pure Docker Desktop (at least not when I tried it last). It sounds like you're using WSL (/mnt is normally associated with that) with Docker Desktop so I'll have to update the readme to mention that as an option. Thanks for the heads-up there.
