### ISSUE TITLE
pv-pvc-sc-cm example fails on macOS BigSur 11.2.3 with docker-desktop

### ISSUE THREAD

**Issue by Caleb9** [DanWahlin/DockerAndKubernetesCourseCode#17]
The *pv-pvc-sc-cm* example does not work on macOS BigSur 11.2.3 because `/tmp` is actually a symbolic link to `/private/tmp`.

Replacing the `/tmp/data/db` with `/private/tmp/data/db` fixed it for me. Here's the line that I had to change to make it work:
https://github.com/DanWahlin/DockerAndKubernetesCourseCode/blob/bdab8df93e84cc6ad23502f1e1b97b630a907a9e/samples/volumes/pv-pvc-sc-cm/mongo.deployment.yml#L54

**Comment by DanWahlin** [comment]
Thanks for sharing @Caleb9! There are definitely several tricks across OSes (especially Windows) so I appreciate you sharing that info about BirSur. I'll update that file with a comment to mention that. Really appreciate it!

**Comment by DanWahlin** [comment]
Updated:

https://github.com/DanWahlin/DockerAndKubernetesCourseCode/blob/main/samples/volumes/pv-pvc-sc-cm/mongo.deployment.yml
