### ISSUE TITLE
configMaps : Readme.md and file name mismatch

### ISSUE THREAD

**Issue by aravinthkumar** [DanWahlin/DockerAndKubernetesCourseCode#19]
In the [readme.md](https://github.com/DanWahlin/DockerAndKubernetesCourseCode/blob/main/samples/configMaps/readme.md)  under configMaps the step 2

`Load settings from a file: kubectl create cm app-settings --from-file=settings.properties. Will add file name as key into ConfigMap data. Will NOT add quotes around non-string values.`  talks about `setting.properties` and file present in the folder is  is `setting.config` .

Could you have a look :)

**Comment by DanWahlin** [comment]
Thanks! I fixed the filename in the readme.
