### ISSUE TITLE
[Perf] JsonSerializationOptions instances should be reused

### ISSUE THREAD

**Issue by sebastienros** [DanWahlin/DockerAndKubernetesCourseCode#28]
https://github.com/DanWahlin/DockerAndKubernetesCourseCode/blob/main/labs/Monolith%20to%20Microservices/End/Microservices/MonolithToMicroservices/Repository/CustomersRepository.cs#L35

Creating such options creates a lock and is not suitable to be created over and over. This should be a static property that is reused.

**Comment by DanWahlin** [comment]
Thanks! Appreciate you calling that out @sebastienros.
